# Import Travis configuration from dev-tools repo
version: ~> 1.0
import:
  - source: humanmade/altis-dev-tools:travis/module.yml@deaed48
    mode: merge

# Add your custom config below, which will merge with the default module config from the section above.
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - cd $HOME/test-root && composer server start
  - cd $HOME/test-root && composer server db info
  - cd $HOME/test-root && composer server db exec -- "select * from wp_site;"
  - cd $HOME/test-root && composer server status
  - cd $HOME/test-root && composer server exec -- ls -al
  - cd $HOME/test-root && composer server cli site list
  - cd $HOME/test-root && composer server stop --clean
  - cd $HOME/test-root && composer server destroy --clean
