name: CI

on:
  push:
    branches:
      - master
      - main
      - 'v*-branch'
  pull_request:
    branches:
      - master
      - main
      - 'v*-branch'

jobs:
  ci:
    uses: humanmade/altis-dev-tools/.github/workflows/module-ci.yml@4050cfac8dccff8b328b64726dccb90fec707d4
    with:
      altis-package: altis/local-server
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
